name: Schedule Health Check pipeline

on:
  schedule:
    - cron: "*/1 * * * *" # Schedule to run at 1 minute

  push:
    branches:
      - main

jobs:
  health_check_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check url health state
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-jxm7.onrender.com/health
