name: Schedule Health Check pipeline

on:
  push
  # schedule:
  #   - cron: "00 12,13 * * *"

jobs:
  health_check_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check url health state
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex-jxm7.onrender.com/health
  #     - name:
